"""Emit carved (subtract_nuclei=true) variants of the vscyto3d-ablation membrane leaves.

The ablation tables (ablation_vscyto3d_init.md) score membrane no-carve for an
identical-pipeline comparison, so the ablation tracks (randinit / cytoland /
infectionft) lack the nucleus-carved membrane instance metrics the main benchmark
reports. This emits the SECONDARY carved variant for those tracks. Mirrors
``make_carved_membrane_leaves.py`` but targets the per-variant ablation leaves
(single for ``eval__ipsc_confocal``, grouped for ``eval__a549_mantis``) rather
than the grouped main-benchmark buckets.

Transformation, identical to the grouped tool:

  - segmentation.watershed.subtract_nuclei -> true (carve the shared nucleus core
    out, leaving only the cytoplasm shell), and
  - save.save_dir (single leaf) or every conditions[].save.save_dir (grouped) ->
    a sibling with a ``_carved`` suffix, so carved CSVs never overwrite the
    no-carve headline results.

Cache dirs are deliberately unchanged: the deep/CP feature caches are
carve-independent and stay warm; only the instance-mask cache recomputes for the
carved identity (that recompute IS the work, and it overwrites the no-carve
instance-MASK cache in the shared dirs — the no-carve final CSVs are untouched).

Carved leaves land in a ``{variant}_carved/`` sibling dir, preserving the exact
``eval__{ipsc_confocal,a549_mantis}`` basenames so ``run_eval_direct.slurm`` still
routes ``a549_mantis`` to ``evaluate-grouped``.

    uv run python applications/dynacell/tools/make_carved_ablation_membrane_leaves.py
    sbatch applications/dynacell/tools/run_eval_direct.slurm \
        membrane/fcmae_vscyto3d_pretrained_randinit/randinit_carved/eval__ipsc_confocal \
        <focus + GLCM overrides>
"""

from __future__ import annotations

from pathlib import Path

import yaml

_LEAF = Path(__file__).resolve().parent.parent / ("configs/benchmarks/virtual_staining/_internal/leaf/membrane")
_VARIANTS = (
    "fcmae_vscyto3d_pretrained_randinit/randinit",
    "fcmae_vscyto3d_pretrained_cytoland/cytoland",
    "fcmae_vscyto3d_pretrained_infectionft/infectionft",
)
_TESTSETS = ("eval__ipsc_confocal", "eval__a549_mantis")
_HEADER = (
    "# @package _global_\n"
    "# CARVED variant (segmentation.watershed.subtract_nuclei=true) of {src}.\n"
    "# Secondary cytoplasm-boundary-fidelity metric; no-carve is the ablation headline.\n"
    "# Generated by tools/make_carved_ablation_membrane_leaves.py.\n"
)


def carve(src_rel: str) -> Path:
    """Write the carved variant of one ablation membrane leaf; return its path."""
    body = yaml.safe_load((_LEAF / f"{src_rel}.yaml").read_text())
    body["segmentation"]["watershed"]["subtract_nuclei"] = True
    if "conditions" in body:
        for cond in body["conditions"]:
            cond["save"]["save_dir"] = f"{cond['save']['save_dir']}_carved"
    else:
        body["save"]["save_dir"] = f"{body['save']['save_dir']}_carved"
    model_dir, variant, basename = src_rel.split("/")
    out = _LEAF / model_dir / f"{variant}_carved" / f"{basename}.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_HEADER.format(src=src_rel) + yaml.safe_dump(body, default_flow_style=False, sort_keys=False))
    return out


def main() -> int:
    """Emit carved variants for every ablation membrane leaf."""
    for variant in _VARIANTS:
        for testset in _TESTSETS:
            out = carve(f"{variant}/{testset}")
            print(f"  wrote {out.relative_to(_LEAF.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
