"""Emit carved (subtract_nuclei=true) variants of the membrane grouped leaves.

The headline whole-cell instance AP is no-carve (full cell, subtract_nuclei=false)
— see project_wholecell_ap_carve. This produces the SECONDARY "cytoplasm-boundary
fidelity" variant for the same membrane buckets: identical leaves except

  - segmentation.watershed.subtract_nuclei -> true (carve the shared nucleus core
    out, leaving only the cytoplasm shell), and
  - every condition's save.save_dir -> a sibling with a ``_carved`` suffix, so the
    carved CSVs never overwrite the no-carve headline results.

Cache dirs (pred_cache_dir in-leaf; gt_cache_dir derived) are deliberately NOT
changed: the deep/CP feature caches are carve-independent and stay warm, so only
the instance-mask cache recomputes for the carved identity (that recompute IS the
work). The trade-off is that the carved run overwrites the no-carve instance-MASK
cache in the shared dirs; the no-carve final CSVs are untouched, so the headline
results are safe — only a future no-carve re-run would re-segment.

Run each carved bucket leaf via the single-leaf launcher (it auto-detects
``evaluate-grouped`` for grouped leaves), passing the focus + GLCM eval overrides:
    uv run python applications/dynacell/tools/make_carved_membrane_leaves.py
    sbatch applications/dynacell/tools/run_eval_direct.slurm \
        configs/benchmarks/virtual_staining/_internal/leaf/grouped/membrane_a549_trained_carved/eval_grouped \
        <focus + GLCM overrides>
"""

from __future__ import annotations

from pathlib import Path

import yaml

_GROUPED = Path(__file__).resolve().parent.parent / ("configs/benchmarks/virtual_staining/_internal/leaf/grouped")
_BUCKETS = ("membrane_joint", "membrane_a549_trained", "membrane_ipsc_trained")
_HEADER = (
    "# @package _global_\n"
    "# CARVED variant (segmentation.watershed.subtract_nuclei=true) of {bucket}.\n"
    "# Secondary cytoplasm-boundary-fidelity metric; no-carve is the headline.\n"
    "# Generated by tools/make_carved_membrane_leaves.py from {bucket}/eval_grouped.yaml.\n"
)


def carve_leaf(bucket: str) -> Path:
    """Write the carved variant of one membrane grouped leaf; return its path."""
    body = yaml.safe_load((_GROUPED / bucket / "eval_grouped.yaml").read_text())
    body["segmentation"]["watershed"]["subtract_nuclei"] = True
    for cond in body["conditions"]:
        cond["save"]["save_dir"] = f"{cond['save']['save_dir']}_carved"
    out = _GROUPED / f"{bucket}_carved" / "eval_grouped.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_HEADER.format(bucket=bucket) + yaml.safe_dump(body, default_flow_style=False, sort_keys=False))
    return out


def main() -> int:
    """Emit carved variants for every membrane grouped bucket."""
    for bucket in _BUCKETS:
        out = carve_leaf(bucket)
        n = len(yaml.safe_load(out.read_text())["conditions"])
        print(f"  wrote {out.relative_to(_GROUPED.parent)} ({n} conditions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
