"""Generate per-store biahub-concatenate configs to copy Zuben's 25 v2 gut stores to v3.

Each of Zuben's stores is one gut = one experiment = a single position ``A/1/0`` with the
four channels ``[nuclear, septate, brush_border, SuH]``. We convert each store to its own
v3 store under ``OUTPUT_ROOT`` preserving the original basename and the ``A/1/0`` layout, so
the cell-index parquet's ``(store_path, well, fov)`` mapping stays valid — only the
``store_path`` directory changes.

Emits, per store, ``configs/<stem>.yml`` and a single ``submit_all.sh`` that runs
``biahub concatenate`` (conda env ``biautils``) for every store as SLURM jobs.

Run::

    uv run --no-sync python applications/dynaclr/configs/collections/zuben_gut/gen_convert_v3.py
    bash <this_dir>/convert_v3/submit_all.sh
"""

import os
from pathlib import Path

import pandas as pd

PARQUET = "/hpc/projects/jacobo_group/zuben/proj/gutCellClassifier/data/dynaclr_cell_index_bbox_center.parquet"
OUTPUT_ROOT = "/hpc/projects/organelle_phenotyping/datasets/zuben_gut_development"
CHANNELS = ["nuclear", "septate", "brush_border", "SuH"]
CHUNKS_CZYX = [1, 16, 256, 256]
SHARDS_RATIO = [1, 1, 4, 8, 8]
OME_VERSION = "0.5"
BIAHUB_ENV = "biautils"

HERE = Path(__file__).resolve().parent
WORKDIR = HERE / "convert_v3"
CONFIGS_DIR = WORKDIR / "configs"


def _yaml_config(store_path: str) -> str:
    import yaml

    cfg = {
        # One input FOV glob per data path: this store's single position A/1/0.
        "concat_data_paths": [f"{store_path}/A/1/*"],
        "time_indices": "all",
        # List-of-lists: one channel list per data path (here, one path).
        "channel_names": [list(CHANNELS)],
        "X_slice": "all",
        "Y_slice": "all",
        "Z_slice": "all",
        "chunks_czyx": list(CHUNKS_CZYX),
        "shards_ratio": list(SHARDS_RATIO),
        "output_ome_zarr_version": OME_VERSION,
    }
    return yaml.safe_dump(cfg, default_flow_style=False, sort_keys=False)


def main() -> None:
    """Emit one biahub-concatenate config per store plus a SLURM submit driver."""
    df = pd.read_parquet(PARQUET, columns=["store_path"])
    stores = sorted(df["store_path"].astype(str).unique())

    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    submit_lines = [
        "#!/bin/bash",
        "set -euo pipefail",
        "# Auto-generated by gen_convert_v3.py. Submits one biahub concatenate per store.",
        f"mkdir -p {OUTPUT_ROOT}",
        "",
    ]

    for store in stores:
        stem = os.path.basename(store)  # e.g. AAY6_sox21a_d0_63x_gut1.zarr
        cfg_path = CONFIGS_DIR / f"{stem.replace('.zarr', '')}.yml"
        cfg_path.write_text(_yaml_config(store))
        out_path = f"{OUTPUT_ROOT}/{stem}"
        submit_lines.append(f'echo "=== {stem} ==="')
        submit_lines.append(
            f"conda run -n {BIAHUB_ENV} biahub concatenate "
            f'-c "{cfg_path}" -o "{out_path}" -m -sb "{WORKDIR / "sbatch_overrides.sh"}"'
        )
        submit_lines.append("")

    (WORKDIR / "submit_all.sh").write_text("\n".join(submit_lines) + "\n")
    (WORKDIR / "sbatch_overrides.sh").write_text(
        "#!/bin/bash\n#SBATCH --partition=cpu\n#SBATCH --cpus-per-task=4\n#SBATCH --mem-per-cpu=32G\n"
    )

    print(f"Generated {len(stores)} configs under {CONFIGS_DIR}")
    print(f"Submit driver: {WORKDIR / 'submit_all.sh'}")
    print(f"Output root:   {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()
