# UNetViT3D: supervised training.
# Usage: cd applications/dynacell/examples/configs && uv run dynacell fit -c unetvit3d/fit.yml
base:
  - ../recipes/trainer/fit_4gpu.yml
  - ../recipes/data/hcs_phase_fluor_3d.yml
  - ../recipes/models/unetvit3d.yml

model:
  init_args:
    lr: 0.0002
    schedule: WarmupCosine

trainer:
  max_epochs: 200

data:
  init_args:
    data_path: #TODO HCS OME-Zarr data
    z_window_size: 8
    batch_size: 8
    yx_patch_size: [512, 512]
