coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
