output_dir: '/data/xyz'
verbose: 10
input_dir: '/data/abc'
slice_ids: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
pos_ids: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 25, 26, 28, 34, 39]
channel_ids: [1, 7]
num_workers: 4
resize:
    scale_factor: [4.85, 1.0, 1.0]
    num_slices_subvolume: 10
    resize_3d: True
flat_field:
    method: 'from_file'
    flat_field_channels: [1, 7]
    flat_field_dir: '/data/flat_field_images'
uniform_structure: True
masks:
    channels: [7]
    str_elem_radius: 3
    mask_type: 'unimodal'
tile:
    tile_size: [128, 128, 64]
    step_size: [96, 96, 48]
    depths: [1, 1]
    image_format: 'zyx'
    tile_3d: True
    mask_channel: 8
    min_fraction: 0.25
    mask_dir: '/data/../tst_debug_preprocess/mask_channels_7'

