output_dir: '/data/sguo/Processed/2018_11_01_kidney_slice/SMS_2018_1101_1906_1_BG_2018_1101_1906_1/test_master'
verbose: 10
input_dir: '/data/sguo/Processed/2018_11_01_kidney_slice/SMS_2018_1101_1906_1_BG_2018_1101_1906_1/microDL_format'
correct_flat_field: False
uniform_structure: True
create_masks: False
masks:
    channels: [5]
    str_elem_radius: 3
do_tiling: True
tile:
    channels: [0,1]
    tile_size: [256, 256]
    step_size: [128, 128]
    depths: [1, 1]
    mask_depth: 1
    shape_order: 'zyx'
    num_workers: 4
slice_ids: [0, 1]
pos_ids: [3, 4]
