model_dir: '/gpfs/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/kidney_translation_models/model25d/'
image_dir: '/gpfs/CompMicro/projects/Rickettsia/2022_RickettsiaAnalysis_Soorya/3_Cell_Image_Preprocessing/VirtualStainingMicroDL_KidneyMBL/data/'
preprocess_dir: '/gpfs/CompMicro/projects/Rickettsia/2022_RickettsiaAnalysis_Soorya/3_Cell_Image_Preprocessing/VirtualStainingMicroDL_KidneyMBL/Preprocessed_temp_2'
dataset:
  input_channels: [3]
  target_channels: [0]
  slice_ids: [10, 11, 12, 13, 14, 15]
images:
    image_format: 'zyx'
    image_ext: '.tif'
    name_format: sms
    pred_chan_name: 'pred'
save_to_image_dir: False
data_split: test
save_figs: True
metrics:
    metrics: ['r2', 'corr', 'ssim']
    metrics_orientations: ['xy', 'xyz', 'xz', 'yz']