model_dir: '/data/models'
model_fname: 'kidney_3d/Model_2019.hdf5'
image_dir: '/data/kidney_tiles/resized_images'
image_params_dict:
    image_format: 'zyx'
    im_ext: '.npy'
    crop_shape: [96, 2048, 2048]
metrics: ['r2', 'corr', 'ssim']
metrics_orientations: ['xy', 'xyz', 'xz', 'yz']
mask_params_dict:
    mask_dir: '/data/kidney_tiles/mask_channels_2'
    mask_channel: 9
vol_inf_dict:
    tile_shape: [96, 512, 512]
    num_overlap: [0, 32, 32]
    overlap_operation: 'mean'