dataset:
    preprocess: False
    data_dir: '/data/image_tile_256-256_step_256-256'
    input_channels: [3]
    target_channels: [4]
    split_by_column: pos_idx
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/data/labelfree_tile256_bs16_mse_clr_nadam'
    batch_size: 16
    max_epochs: 50
    patience: 20
    metrics: dice_coef
    loss: dice_coef_loss
    callbacks:
        LearningRateScheduler:
            lr_find: True
            base_lr: 0.0001
            max_lr: 0.01
            max_epochs: 3
            fig_fname: '/data/lr_finder_result.png'
    optimizer:
        lr: 0.001
        name: Nadam
network:
    class: UNet2D
    num_filters_per_block: [16, 32, 64, 96, 128]
    num_convs_per_block: 2
    filter_size: 3
    batch_norm: True
    activation: relu
    pooling_type: max
    skip_merge_type: concat
    upsampling: bilinear
    dropout: 0.2
    residual: True
    height: 256
    width: 256
    num_input_channels: 1
    num_target_channels: 1
    data_format: 'channels_first'
    dropout_dense: 0.4
    final_activation: sigmoid
