dataset:
    data_dir: '/hpc/projects/CompMicro/projects/virtualstaining/MBL_DL_image_translation/temp/tile_small_25D/tiles_256-256_step_128-128'
    input_channels: [3]
    target_channels: [0]
    train_fraction: 1
    split_by_column: pos_idx
    model_task: 'regression'
    normalize: False
    mask_channels: [4]
    random_seed: 42
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    augmentation: True
verbose: 10
trainer:
    model_dir: '/hpc/projects/compmicro/projects/virtualstaining/torch_microDL_models/Unet25d'
    batch_size: 16
    max_epochs: 5
    metrics: coeff_determination
    loss: mae_loss
    num_workers: 32
    callbacks:
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 50
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.001
        name: Adam
network:
    class: UNetStackTo2D
    num_input_channels: 1
    data_format: 'channels_first'
    height: 256
    width: 256
    depth: 5
    batch_norm: True
    pooling_type: average
    filter_size: 3
    activation:
        type: relu
    dropout: 0.2
    num_filters_per_block: [16, 32, 64, 128, 256]
    num_convs_per_block: 2
    block_sequence: conv-activation-bn
    skip_merge_type: concat
    upsampling: bilinear
    residual: True
    num_target_channels: 1
    final_activation: linear
