model_dir: '/gpfs/CompMicro/projects/virtualstaining/torch_microDL/models/tensorflow_models/Unet25d/MBL_DL_pretrained_2021_09_29'
image_dir: '/gpfs/CompMicro/projects/virtualstaining/torch_microDL/data/2022_09_07_Soorya_KidneyRickettsia/data'
preprocess_dir: '/gpfs/CompMicro/projects/virtualstaining/torch_microDL/data/2022_09_07_Soorya_KidneyRickettsia/tile_25D'
dataset:
  input_channels: [3]
  target_channels: [0]
  slice_ids: [10, 11, 12, 13, 14, 15]
images:
    image_format: 'zyx'
    image_ext: '.tif'
    name_format: sms
    pred_chan_name: 'pred'
save_to_image_dir: False
data_split: test
save_figs: True
metrics:
    metrics: ['r2', 'corr', 'ssim']
    metrics_orientations: ['xy', 'xyz', 'xz', 'yz']