datamodule_class: viscy.data.triplet.TripletDataModule
datamodule:
  data_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_11_07_A549_SEC61_ZIKV_DENV/2-assemble/2024_11_07_A549_SEC61_DENV.zarr
  tracks_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_11_07_A549_SEC61_ZIKV_DENV/1-preprocess/label-free/4-track-gt/2024_11_07_A549_SEC61_ZIKV_DENV_2_cropped.zarr
  batch_size: 32
  final_yx_patch_size:
  - 192
  - 192
  include_fov_names: null
  include_track_ids: null
  initial_yx_patch_size:
  - 192
  - 192
  normalizations:
  - class_path: viscy.transforms.ScaleIntensityRangePercentilesd
    init_args:
      b_max: 1.0
      b_min: 0.0
      keys:
      - Phase3D
      lower: 50
      upper: 99
  - class_path: viscy.transforms.ScaleIntensityRangePercentilesd
    init_args:
      b_max: 1.0
      b_min: 0.0
      keys:
      - raw GFP EX488 EM525-45
      lower: 50
      upper: 99
  num_workers: 10
  source_channel:
  - Phase3D
  - raw GFP EX488 EM525-45
  z_range:
  - 25
  - 40
embedding:
  pca_kwargs:
    n_components: 8
  phate_kwargs:
    decay: 40
    knn: 5
    n_components: 2
    n_jobs: -1
    random_state: 42
  reductions:
  - PHATE
  - PCA
execution:
  overwrite: false
  save_config: true
  show_config: true
model:
  model_name: facebook/sam2-hiera-base-plus
  channel_reduction_methods:
    Phase3D: middle_slice
    raw GFP EX488 EM525-45: max
paths:
  output_path: /home/eduardo.hirata/repos/viscy/applications/benchmarking/DynaCLR/SAM2/sam2_sec61b_n_phase_all_highresfeats0.zarr
