# Example Lightning config using CollectionTripletDataModule with W&B tracking
# This config fetches dataset paths from Airtable collections and logs to W&B
# Usage: viscy fit -c examples/airtable/train_with_wandb.yml

seed_everything: 42

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  default_root_dir: logs/wandb  # W&B will create versioned subdirs
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: viscy-experiments
      entity: null  # Set to your W&B team name or leave null for personal
      log_model: false  # Don't upload checkpoints to W&B (too large)
      save_dir: ./logs  # Explicit save directory for config files
      name: null  # Auto-generate unique run name
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: loss/val
        save_top_k: 3
        save_last: true
    - class_path: viscy.airtable.callbacks.CollectionWandbCallback
      # No init_args needed - automatically logs collection metadata

model:
  class_path: viscy.representation.engine.ContrastiveModule
  init_args:
    encoder:
      class_path: viscy.representation.contrastive.ContrastiveEncoder
      init_args:
        backbone: convnext_tiny
        in_channels: 1
        in_stack_depth: 5
        stem_kernel_size: [5, 4, 4]
        stem_stride: [5, 4, 4]
        embedding_dim: 768
        projection_dim: 32
    loss_function:
      class_path: pytorch_metric_learning.losses.NTXentLoss
      init_args:
        temperature: 0.05
    lr: 0.0002
    log_batches_per_epoch: 3
    log_samples_per_batch: 3
    example_input_array_shape: [1, 1, 5, 160, 160]


data:
  # NEW: Use CollectionTripletDataModule for Airtable collection integration
  class_path: viscy.airtable.factory.CollectionTripletDataModule
  init_args:
    # Airtable collection parameters
    base_id: "app8vqaoWyOwa0sB5"  # Replace with your base ID
    collection_name: "2024_11_07_A549_SEC61_DENV_wells_B1_B2"
    collection_version: "0.0.1"

    # TripletDataModule parameters
    source_channel: [Phase3D]
    z_range: [10, 15]
    z_window_size: 5
    initial_yx_patch_size: [160, 160]
    final_yx_patch_size: [160, 160]
    batch_size: 16
    num_workers: 1
    split_ratio: 0.8
    time_interval: any

    # Optional: Override collection FOVs with specific wells
    fit_include_wells: ["B/1", "B/2"]
