datamodule_class: viscy.data.triplet.TripletDataModule
datamodule:
  data_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_02_04_A549_DENV_ZIKV_timelapse/8-train-test-split/registered_test.zarr
  tracks_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_02_04_A549_DENV_ZIKV_timelapse/8-train-test-split/track_test.zarr
  batch_size: 32
  final_yx_patch_size:
  - 256
  - 256
  include_fov_names: null
  include_track_ids: null
  initial_yx_patch_size:
  - 256
  - 256
  normalizations:
  - class_path: viscy.transforms.ScaleIntensityRangePercentilesd
    init_args:
      b_max: 1.0
      b_min: 0.0
      keys:
      - RFP
      lower: 50
      upper: 99
  - class_path: viscy.transforms.NormalizeIntensityd
    init_args:
      keys:
      - Phase3D
  num_workers: 10
  source_channel:
  - RFP
  - Phase3D
  z_range:
  - 15
  - 45

embedding:
  pca_kwargs:
    n_components: 8
  phate_kwargs:
    decay: 40
    knn: 5
    n_components: 2
    n_jobs: -1
    random_state: 42
  reductions:
  - PHATE
  - PCA

execution:
  overwrite: false
  save_config: true
  show_config: true

model:
  model_name: facebook/dinov3-convnext-tiny-pretrain-lvd1689m
  pooling_method: mean  # Options: "mean", "max", "cls_token"
  middle_slice_index: 18  # Specific z-slice index (if null, uses D//2)
  channel_reduction_methods:
    Phase3D: middle_slice
    RFP: max
  channel_names:
  - RFP
  - Phase3D

paths:
  output_path: /hpc/mydata/eduardo.hirata/repos/viscy/applications/benchmarking/DynaCLR/DINOV3/embeddings_convnext_tiny_mean.zarr
