# Export the FCMAE-pretrained VSCyto2D weights to ONNX format
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  callbacks: []
model:
  class_path: viscy.translation.engine.VSUNet
  init_args:
    architecture: fcmae
    model_config:
      in_channels: 1
      out_channels: 2
      encoder_blocks: [3, 3, 9, 3]
      dims: [96, 192, 384, 768]
      decoder_conv_blocks: 2
      stem_kernel_size: [1, 2, 2]
      in_stack_depth: 1
      pretraining: False
# TODO: output path for the exported model
export_path: /path/to/exported.onnx
# TODO: path to the checkpoint file
# Download from:
# https://public.czbiohub.org/comp.micro/viscy/VS_models/VSCyto2D/VSCyto2D/epoch=399-step=23200.ckpt
ckpt_path: /path/to/trained.ckpt
format: onnx
