# Trainer recipe: single-GPU prediction.
trainer:
  accelerator: gpu
  devices: 1
  precision: 32-true
  callbacks:
    - class_path: viscy_utils.callbacks.prediction_writer.HCSPredictionWriter
      init_args:
        output_store: #TODO output zarr path
return_predictions: false
ckpt_path: #TODO checkpoint path
