name: Lint and Test

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "viscy"
          options: "--check --verbose"
      - uses: chartboost/ruff-action@v1
        with:
          src: "viscy"

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install cpu wheels only to speed up the build
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip install ".[metrics,dev]"
      - name: Test with pytest
        run: pytest -v
